version: "3.8"
services:

front-end:
    stdin_open: true
    image: front-ecommerce
    ports:
      - "4000:3000"
    networks:
      - integrify-full

back-end:
    image: back-ecommerce
    ports:
        -"6000:5000"
    networks:
        -integrify-full
    depends_on:
        - db

db:
    image: mongo:3.6.23-xenial
    ports:
        -"27017:27017"
    networks:
        -integrify-full
networks:
    integrify-full:
        driver: bridge